translations = {
    'en': {
        'qhyccd_capture': {
            'connect_settings': 'Connection Settings',
            'settings': 'Settings',
            'status': 'Status:',
            'select_camera': 'Select Camera:',
            'single_frame_mode': 'Single Frame Mode',
            'continuous_mode': 'Continuous Mode',
            'record_mode': 'Record Mode:',
            'select_camera_mode': 'Select Camera Mode:',
            'connect': 'Connect',
            'disconnect': 'Disconnect',
            'reset_camera': 'Rescan Camera',
            'not_connected': 'Not Connected',
            'fps': 'FPS: ~',
            'memory': 'Memory:',
            'show_camera_settings': 'Show Camera Settings',
            'show_capture_control': 'Show Capture Control',
            'show_image_control': 'Show Image Control',
            'show_temperature_control': 'Show Temperature Control',
            'show_cfw_control': 'Show CFW Control',
            'show_video_control': 'Show Video Control',
            'camera_settings': 'Camera Settings',
            'readout_mode': 'Readout Mode:',
            'pixel_bin': 'Pixel Bin:',
            'image_depth': 'Image Depth:',  
            'debayer_mode': 'Debayer Mode:',
            'debayer_mode_true': 'True',
            'debayer_mode_false': 'False',
            'set_resolution': 'Set Resolution',
            'reset_resolution': 'Reset',
            'reset_resolution_tooltip': 'Reset to initial camera resolution',
            'resolution': 'Resolution',
            'roi': 'ROI',
            'roi_tooltip': 'ROI (Click once to set the start point, click again to set the end point)',
            'x': 'x:',
            'y': 'y:',
            'w': 'w:',
            'h': 'h:',
            'capture_control': 'Capture Control',
            'exposure_time': 'Exposure Time:',
            'gain': 'Gain:',
            'offset': 'Offset:',
            'usb_traffic': 'USB Traffic:',
            'distributed_display': 'Distributed Display',
            'single_display': 'Single Display',
            'sequential_display': 'Sequential Display',
            'display_mode': 'Display Mode:',
            'bayer_conversion': 'Bayer Conversion:',
            'start_capture': 'Start Capture',
            'save': 'Save',
            'save_tooltip': 'Save the last captured image without image processing',
            'recording': 'Recording',
            'preview_mode': 'Preview Mode',
            'preview_mode_tooltip': 'In preview mode, the camera outputs image data in real-time and displays it in the window',
            'top_checkbox': 'Topmost',
            'top_checkbox_tooltip': 'When checked, the image will be displayed on top',
            'single_frame_storage': 'Single Frame Storage',
            'video_storage': 'Video Storage',
            'save_mode': 'Save Mode:',
            'select_path': 'Select Path',
            'record_path': 'Recording Path:',
            'record_file_name': 'File Name:',
            'time_mode': 'Time Mode',
            'frame_mode': 'Frame Mode',
            'seconds': ' Seconds',
            'record_time': 'Recording Time:',
            'record_frames': 'Recording Frames:',
            'start_record': 'Start Recording',
            'stop_record': 'Stop Recording',
            'record_progress': 'Recording Progress:',
            'image_processing': 'Image Processing',
            'histogram': 'Histogram',
            'show_histogram': 'Show Histogram',
            'white_balance_control': 'White Balance Control',
            'red': 'Red:',
            'green': 'Green:',
            'blue': 'Blue:',
            'temperature_control': 'Temperature Control',
            'set_temperature': 'Set Temperature:',
            'temperature': 'Temperature: Unknown',
            'humidity': 'Humidity: Unknown',
            'CFW_control': 'CFW Control',
            'CFW_position': 'CFW',
            'init_complete': 'Initialization Complete',
            'connected': 'Camera Connection Complete',
            'disconnected': 'Camera Disconnected',
            'capturing': 'Capturing',
            'capture_complete': 'Capture Complete',
            'update_camera_color': 'Determine if the camera is color',
            'update_limit_selector': 'Update parameter limits',
            'update_camera_config': 'Update camera configuration',
            'update_bin_mode': 'Update bin mode',
            'update_depth_mode': 'Update depth mode',
            'update_resolution': 'Update resolution',
            'update_camera_mode': 'Update camera mode',
            'update_temperature_control': 'Update temperature control',
            'update_CFW_control': 'Update CFW control',
            'set_resolution': 'Set Resolution:',
            'cancel_capture': 'Cancel Capture',
            'capture_finished': 'Capture Finished!',
            'capture_canceled': 'Capture Canceled',
            'save_image': 'Save Image',
            'save_image_failed': 'Image Save Failed',
            'apply_roi': 'Apply ROI',
            'select_save_path': 'Select Save Path',
            'saving': 'Saving...',
            'save_completed': 'Save Completed',
            'init_failed': 'Initialization Failed',
            'save_image_success': 'Image Saved to',
            'set_exposure_time_success': 'Set Exposure Time Success',
            'set_gain_success': 'Set Gain Success',
            'set_offset_success': 'Set Offset Success',
            'set_usb_traffic_success': 'Set USB Traffic Success',
            'roi_activated': 'ROI mode activated, please click on the image to select the area',
            'roi_closed': 'ROI mode closed',
            'set_red_gain_success': 'Set Red Gain Success',
            'set_green_gain_success': 'Set Green Gain Success',
            'set_blue_gain_success': 'Set Blue Gain Success',
            'set_temperature_success': 'Set Temperature Success',
            'set_cfw_filter_success': 'Set CFW Filter Success',
            'camera_info_name': 'Camera Name',
            'camera_info_chip': 'Chip Size',
            'camera_info_image': 'Image Resolution',
            'camera_info_pixel': 'Pixel Size',
            'camera_info_disconnected': 'Disconnected',
            'start_recording': 'Start Recording',
            'recording_completed': 'Recording Completed',
            'stop_recording': 'Stop Recording',
            'settings_loaded': 'Settings Loaded',
            'update_camera_name': 'Rescan Camera',
            'update_readout_mode': 'Update Readout Mode:',
            'update_pixel_bin': 'Update Pixel Bin:',
            'update_depth': 'Update Depth:',
            'update_debayer_mode': 'Update Debayer Mode:',
        },
        'setting': {
            'settings': 'Settings',
            'language': 'Language',
            'apply': 'Apply',
            'cancel': 'Cancel',
            'reset': 'Reset',
            'settings_saved': 'Settings saved.',
            'settings_saved_message': 'Changes will take effect after restart.',
            'select_qhyccd_path': 'Select SDK Path',
        },
        'captureStatus': {
            'capturing': 'Capturing.. ',
            'capturing_1': 'Capturing.  ',
            'capturing_2': 'Capturing...',
            'exposure': 'Exposure:',
        },
        'histogramWidget': {
            'histogram': 'Histogram',
        },
        'camera_thread': {
            'start_connect': 'Start Connecting Camera...',
            'camera_connected_failed': 'Camera Connected Failed.',
            'camera_connected': 'Camera Connected Successfully.',
            'get_qhyccd_number_of_read_modes': 'Get QHYCCD Number Of Read Modes...',
            'get_qhyccd_number_of_read_modes_failed': 'Get QHYCCD Number Of Read Modes Failed.',
            'get_qhyccd_number_of_read_modes_success': 'Get QHYCCD Number Of Read Modes Successfully.',
            'set_qhyccd_read_mode': 'Set QHYCCD Read Mode...',
            'set_qhyccd_read_mode_failed': 'Set QHYCCD Read Mode Failed.',
            'set_qhyccd_read_mode_success': 'Set QHYCCD Read Mode Successfully.',
            'set_qhyccd_stream_mode': 'Set QHYCCD Stream Mode...',
            'set_qhyccd_stream_mode_failed': 'Set QHYCCD Stream Mode Failed.',
            'set_qhyccd_stream_mode_success': 'Set QHYCCD Stream Mode Successfully.',
            'init_camera': 'Init Camera...',
            'init_camera_failed': 'Init Camera Failed.',
            'init_camera_success': 'Init Camera Successfully.',
            'close_camera': 'Close Camera...',
            'close_camera_failed': 'Close Camera Failed.',
            'close_camera_success': 'Close Camera Successfully.',
            'release_camera_resource': 'Release Camera Resource...',
            'release_camera_resource_failed': 'Release Camera Resource Failed.',
            'release_camera_resource_success': 'Release Camera Resource Successfully.',
        },
        'debug': {
            'init_failed': 'Initialization Failed',
            'not_found_sdk': 'SDK file not found',
            'camera_connected_failed': 'Camera Connected Failed',
            'unknown_architecture': 'Unknown Architecture',
            'get_qhyccd_id_failed': 'Get QHYCCD ID Failed',
            'get_qhyccd_read_mode_number_failed': 'Get QHYCCD Read Mode Number Failed',
            'get_qhyccd_read_mode_name_failed': 'Get QHYCCD Read Mode Name Failed',
            'set_qhyccd_read_mode_failed': 'Set QHYCCD Read Mode Failed',
            'set_qhyccd_stream_mode_failed': 'Set QHYCCD Stream Mode Failed',
            'init_camera_failed': 'Init Camera Failed',
            'close_camera_failed': 'Close Camera Failed',
            'release_camera_resource_failed': 'Release Camera Resource Failed',
            'disconnect_white_balance_failed': 'Disconnect White Balance Failed',
            'get_qhyccd_param_failed': 'Get QHYCCD Param Failed',
            'get_qhyccd_is_color_camera_failed': 'Get QHYCCD Is Color Camera Failed',
            'get_qhyccd_effective_area_failed': 'Get QHYCCD Effective Area Failed',
            'get_qhyccd_chip_info_failed': 'Get QHYCCD Chip Info Failed',
            'set_qhyccd_bin_mode_failed': 'Set QHYCCD Bin Mode Failed',
            'set_qhyccd_transferbit_failed': 'Set QHYCCD Transferbit Failed',
            'set_qhyccd_resolution_failed': 'Set QHYCCD Resolution Failed',
            'get_qhyccd_param_min_max_step_failed': 'Get QHYCCD Param Min Max Step Failed',
            'set_qhyccd_exposure_time_failed': 'Set QHYCCD Exposure Time Failed',
            'set_qhyccd_gain_failed': 'Set QHYCCD Gain Failed',
            'set_qhyccd_offset_failed': 'Set QHYCCD Offset Failed',
            'set_qhyccd_usb_traffic_failed': 'Set QHYCCD USB Traffic Failed',
            'no_qhy_image': 'No QHY Image',
            'set_red_gain_failed': 'Set QHYCCD Red Gain Failed',
            'set_green_gain_failed': 'Set QHYCCD Green Gain Failed',
            'set_blue_gain_failed': 'Set QHYCCD Blue Gain Failed',
            'set_temperature_failed': 'Set QHYCCD Temperature Failed',
            'set_cfw_filter_failed': 'Set QHYCCD CFW Filter Failed',
            'begin_qhyccd_live_failed': 'Begin QHYCCD Live Failed',
            'stop_qhyccd_live_failed': 'Stop QHYCCD Live Failed',
            'exp_qhyccd_single_frame_failed': 'Exp QHYCCD Single Frame Failed',
            'get_qhyccd_single_frame_failed': 'Get QHYCCD Single Frame Failed',
            'save_image_failed': 'Save Image Failed',
            'set_qhyccd_debayer_mode_failed': 'Set QHYCCD Debayer Mode Failed',
        },
    },
    'zh': {
        'qhyccd_capture': {
            'connect_settings': '连接设置',
            'settings': '设置',
            'status': '状态:',
            'select_camera': '选择相机:',
            'single_frame_mode': '单帧模式',
            'continuous_mode': '连续模式',
            'select_camera_mode': '选择相机模式:',
            'connect': '连接',
            'disconnect': '断开',
            'reset_camera': '重新扫描相机',
            'not_connected': '未连接',
            'fps': 'FPS: ~',
            'memory': '内存:',
            'show_camera_settings': '显示相机设置',
            'show_capture_control': '显示拍摄控制',
            'show_image_control': '显示图像控制',
            'show_temperature_control': '显示温度控制',
            'show_cfw_control': '显示滤镜轮控制',
            'show_video_control': '显示录像控制',
            'camera_settings': '相机设置',
            'readout_mode': '读出模式:',
            'pixel_bin': '像素合并 Bin:',
            'image_depth': '图像位深度:',
            'debayer_mode_true': '启动',
            'debayer_mode_false': '关闭',
            'debayer_mode': 'Debayer模式:',
            'set_resolution': '设置分辨率',
            'reset_resolution': '还原',
            'reset_resolution_tooltip': '还原为相机初始分辨率',
            'resolution': '分辨率',
            'roi': 'ROI',
            'roi_tooltip': 'ROI (鼠标第一次点击确定起始点，第二次点击确定终止点)',
            'x': 'x:',
            'y': 'y:',
            'w': 'w:',
            'h': 'h:',
            'capture_control': '拍摄控制',
            'exposure_time': '曝光时间:',
            'gain': '增益:',
            'offset': '偏移量:',
            'usb_traffic': 'USB 宽带:',
            'distributed_display': '分布式显示',
            'single_display': '单一显示',
            'sequential_display': '序列显示',
            'display_mode': '图像显示方式:',
            'bayer_conversion': 'Bayer 类型转换:',
            'start_capture': '开始拍摄',
            'save': '保存',
            'save_tooltip': '保存最后拍摄的未经过图像处理的图像',
            'recording': '录像',
            'preview_mode': '预览模式',
            'preview_mode_tooltip': '预览模式下，相机将实时输出图像数据，并显示在窗口中',
            'top_checkbox': '是否顶置',
            'top_checkbox_tooltip': '勾选后，图像将顶置显示',
            'single_frame_storage': '单帧存储',
            'video_storage': '视频存储',
            'save_mode': '保存方式:',
            'select_path': '选择路径',
            'record_path': '录像路径:',
            'record_file_name': '文件名:',
            'record_mode': '录像模式:',
            'time_mode': '时间模式',
            'frame_mode': '帧数模式',
            'seconds': ' 秒',
            'record_time': '录像时间:',
            'record_frames': '录像帧数:',
            'start_record': '开始录像',
            'stop_record': '停止录像',
            'record_progress': '录像进度:',
            'image_processing': '图像处理',
            'histogram': '直方图',
            'show_histogram': '显示直方图',
            'white_balance_control': '白平衡控制',
            'red': '红色:',
            'green': '绿色:',
            'blue': '蓝色:',
            'temperature_control': '温度控制',
            'set_temperature': '设置温度:',
            'temperature': '温度',
            'humidity': '湿度',
            'CFW_control': '滤镜轮控制',
            'CFW_position': '滤镜轮',
            'init_complete': '初始化完成',
            'connected': '连接相机完成',
            'disconnected': '断开相机连接',
            'capturing': '正在拍摄',
            'capture_complete': '拍摄完成',
            'update_camera_color': '判断是否为彩色相机',
            'update_limit_selector': '更新参数限制',
            'update_camera_config': '更新相机配置',
            'update_bin_mode': '更新bin模式',
            'update_depth_mode': '更新位深度',
            'update_resolution': '更新分辨率',
            'update_camera_mode': '更新相机模式',
            'update_temperature_control': '更新温度控制',
            'update_CFW_control': '更新滤镜轮控制',
            'set_resolution': '设置分辨率:',
            'cancel_capture': '取消拍摄',
            'capture_finished': '拍摄完成！',
            'capture_canceled': '拍摄已取消',
            'save_image': '保存图像',
            'save_image_failed': '图像保存失败',
            'apply_roi': '应用ROI',
            'select_save_path': '选择保存路径',
            'saving': '保存中...',
            'save_completed': '保存完成',
            'init_failed': '初始化失败',
            'save_image_success': '图像已保存到',
            'set_exposure_time_success': '设置曝光时间成功',
            'set_gain_success': '设置增益成功',
            'set_offset_success': '设置偏移量成功',
            'set_usb_traffic_success': '设置USB带宽成功',
            'roi_activated': 'ROI模式已激活，请在图像上点击以选择区域',
            'roi_closed': 'ROI模式已关闭',
            'set_red_gain_success': '设置红色增益成功',
            'set_green_gain_success': '设置绿色增益成功',
            'set_blue_gain_success': '设置蓝色增益成功',
            'set_temperature_success': '设置温度成功',
            'set_cfw_filter_success': '设置滤镜轮成功',
            'camera_info_name': '相机名称',
            'camera_info_chip': '芯片大小',
            'camera_info_image': '图像分辨率',
            'camera_info_pixel': '像素大小',
            'camera_info_disconnected': '未连接',
            'start_recording': '开始录像',
            'recording_completed': '录像完成',
            'stop_recording': '停止录像',
            'settings_loaded': '设置已加载',
            'update_camera_name': '重新扫描相机',
            'update_readout_mode': '更新读出模式:',
            'update_pixel_bin': '更新像素合并:',
            'update_depth': '更新位深度:',
            'update_debayer_mode': '更新Debayer模式:',
        },
        
        'setting': {
            'settings': '设置',
            'language': '语言',
            'apply': '应用',
            'cancel': '取消',
            'reset': '重置',
            'settings_saved': '设置已保存。',
            'settings_saved_message': '更改将在重启后生效。',
            'select_qhyccd_path': '选择SDK文件',
        },
        'captureStatus': {
            'capturing': '拍摄中.. ',
            'capturing_1': '拍摄中.  ',
            'capturing_2': '拍摄中...',
            'exposure': '曝光:',
        },
        'histogramWidget': {
            'histogram': '直方图',
        },
        'camera_thread': {
            'start_connect': '开始连接相机...',
            'camera_connected_failed': '相机连接失败',
            'camera_connected': '相机连接成功。',
            'get_qhyccd_number_of_read_modes': '获取相机读取模式数量...',
            'get_qhyccd_number_of_read_modes_failed': '获取相机读取模式数量失败。',
            'get_qhyccd_number_of_read_modes_success': '获取相机读取模式数量成功。',
            'set_qhyccd_read_mode': '设置相机读取模式...',
            'set_qhyccd_read_mode_failed': '设置相机读取模式失败。',
            'set_qhyccd_read_mode_success': '设置相机读取模式成功。',
            'set_qhyccd_stream_mode': '设置相机流模式...',
            'set_qhyccd_stream_mode_failed': '设置相机流模式失败。',
            'set_qhyccd_stream_mode_success': '设置相机流模式成功。',
            'init_camera': '初始化相机...',
            'init_camera_failed': '初始化相机失败。',
            'init_camera_success': '初始化相机成功。',
            'close_camera': '开始断开相机连接...',
            'close_camera_failed': '断开相机连接失败。',
            'close_camera_success': '断开相机连接成功。',
            'release_camera_resource': '释放资源...',
            'release_camera_resource_failed': '释放资源失败。',
            'release_camera_resource_success': '释放资源成功。',
        },
        'debug': {
            'init_failed': '初始化失败',
            'not_found_sdk': '未找到SDK文件',
            'camera_connected_failed': '相机连接失败',
            'unknown_architecture': '未知的架构',
            'get_qhyccd_id_failed': '获取相机ID失败',
            'get_qhyccd_read_mode_number_failed': '获取相机读取模式数量失败',
            'get_qhyccd_read_mode_name_failed': '获取相机读取模式名称失败',
            'set_qhyccd_read_mode_failed': '设置相机读取模式失败',
            'set_qhyccd_stream_mode_failed': '设置相机流模式失败',
            'init_camera_failed': '初始化相机失败',
            'close_camera_failed': '关闭相机失败',
            'release_camera_resource_failed': '释放相机资源失败',
            'disconnect_white_balance_failed': '断开白平衡连接失败',
            'get_qhyccd_param_failed': '获取相机参数失败',
            'get_qhyccd_is_color_camera_failed': '获取相机颜色信息失败',
            'get_qhyccd_effective_area_failed': '获取相机有效区域失败',
            'get_qhyccd_chip_info_failed': '获取相机芯片信息失败',
            'set_qhyccd_bin_mode_failed': '设置相机bin模式失败',
            'set_qhyccd_transferbit_failed': '设置相机位深度失败',
            'set_qhyccd_resolution_failed': '设置相机分辨率失败',
            'get_qhyccd_param_min_max_step_failed': '获取相机参数最小值、最大值、步长失败',
            'set_qhyccd_exposure_time_failed': '设置相机曝光时间失败',
            'set_qhyccd_gain_failed': '设置相机增益失败',
            'set_qhyccd_offset_failed': '设置相机偏移量失败',
            'set_qhyccd_usb_traffic_failed': '设置相机USB带宽失败',
            'no_qhy_image': '没有以QHY开头的图片，无法启动ROI模式',
            'set_qhyccd_red_gain_failed': '设置相机红色增益失败',
            'set_qhyccd_green_gain_failed': '设置相机绿色增益失败',
            'set_qhyccd_blue_gain_failed': '设置相机蓝色增益失败',
            'set_qhyccd_temperature_failed': '设置相机温度失败',
            'set_qhyccd_cfw_filter_failed': '设置相机滤镜轮失败',
            'begin_qhyccd_live_failed': '开始预览失败',
            'stop_qhyccd_live_failed': '停止预览失败',
            'exp_qhyccd_single_frame_failed': '单帧曝光失败',
            'get_qhyccd_single_frame_failed': '获取单帧图像数据失败',
            'save_image_failed': '图像保存失败',
            'set_qhyccd_debayer_mode_failed': '设置相机Debayer模式失败',
        },
    },
}