translations = {
    'en': {
        'qhyccd_capture': {
            'connect_settings': 'Connection Settings',
            'settings': 'Settings',
            'status': 'Status:',
            'select_camera': 'Select Camera:',
            'single_frame_mode': 'Single Frame Mode',
            'continuous_mode': 'Continuous Mode',
            'record_mode': 'Record Mode:',
            'select_camera_mode': 'Select Camera Mode:',
            'connect': 'Connect',
            'disconnect': 'Disconnect',
            'reset_camera': 'Rescan Camera',
            'not_connected': 'Not Connected',
            'fps': 'FPS: ~',
            'memory': 'Memory:',
            'show_camera_settings': 'Show Camera Settings',
            'show_capture_control': 'Show Capture Control',
            'show_image_control': 'Show Image Control',
            'show_temperature_control': 'Show Temperature Control',
            'show_cfw_control': 'Show CFW Control',
            'show_video_control': 'Show Video Control',
            'camera_settings': 'Camera Settings',
            'readout_mode': 'Readout Mode:',
            'pixel_bin': 'Pixel Bin:',
            'image_depth': 'Image Depth:',  
            'debayer_mode': 'Debayer Mode:',
            'debayer_mode_true': 'True',
            'debayer_mode_false': 'False',
            'set_resolution': 'Set Resolution',
            'reset_resolution': 'Reset',
            'reset_resolution_tooltip': 'Reset to initial camera resolution',
            'resolution': 'Resolution',
            'roi': 'ROI',
            'roi_tooltip': 'ROI (Click once to set the start point, click again to set the end point)',
            'x': 'x:',
            'y': 'y:',
            'w': 'w:',
            'h': 'h:',
            'capture_control': 'Capture Control',
            'exposure_time': 'Exposure Time:',
            'gain': 'Gain:',
            'offset': 'Offset:',
            'usb_traffic': 'USB Traffic:',
            'distributed_display': 'Distributed Display',
            'single_display': 'Single Display',
            'sequential_display': 'Sequential Display',
            'display_mode': 'Display Mode:',
            'bayer_conversion': 'Bayer Conversion:',
            'start_capture': 'Start Capture',
            'save': 'Save',
            'save_tooltip': 'Save the last captured image without image processing',
            'recording': 'Recording',
            'preview_mode': 'Preview Mode',
            'preview_mode_tooltip': 'In preview mode, the camera outputs image data in real-time and displays it in the window',
            'top_checkbox': 'Topmost',
            'top_checkbox_tooltip': 'When checked, the image will be displayed on top',
            'single_frame_storage': 'Single Frame Storage',
            'video_storage': 'Video Storage',
            'save_mode': 'Save Mode:',
            'select_path': 'Select Path',
            'record_path': 'Recording Path:',
            'record_file_name': 'File Name:',
            'time_mode': 'Time Mode',
            'frame_mode': 'Frame Mode',
            'seconds': ' Seconds',
            'record_time': 'Recording Time:',
            'record_frames': 'Recording Frames:',
            'start_record': 'Start Recording',
            'stop_record': 'Stop Recording',
            'record_progress': 'Recording Progress:',
            'image_processing': 'Image Processing',
            'histogram': 'Histogram',
            'show_histogram': 'Show Histogram',
            'white_balance_control': 'White Balance Control',
            'red': 'Red:',
            'green': 'Green:',
            'blue': 'Blue:',
            'temperature_control': 'Temperature Control',
            'set_temperature': 'Set Temperature:',
            'temperature': 'Temperature: Unknown',
            'humidity': 'Humidity: Unknown',
            'CFW_control': 'CFW Control',
            'CFW_position': 'CFW',
            'init_complete': 'Initialization Complete',
            'connected': 'Camera Connection Complete',
            'disconnected': 'Camera Disconnected',
            'capturing': 'Capturing',
            'capture_complete': 'Capture Complete',
            'update_camera_color': 'Determine if the camera is color',
            'update_limit_selector': 'Update parameter limits',
            'update_camera_config': 'Update camera configuration',
            'update_bin_mode': 'Update bin mode',
            'update_depth_mode': 'Update depth mode',
            'update_resolution': 'Update resolution',
            'update_camera_mode': 'Update camera mode',
            'update_temperature_control': 'Update temperature control',
            'update_CFW_control': 'Update CFW control',
            'set_resolution': 'Set Resolution:',
            'cancel_capture': 'Cancel Capture',
            'capture_finished': 'Capture Finished!',
            'capture_canceled': 'Capture Canceled',
            'save_image': 'Save Image',
            'save_image_failed': 'Image Save Failed',
            'apply_roi': 'Apply ROI',
            'select_save_path': 'Select Save Path',
            'saving': 'Saving...',
            'save_completed': 'Save Completed',
            'init_failed': 'Initialization Failed',
            'save_image_success': 'Image Saved to',
            'set_exposure_time_success': 'Set Exposure Time Success',
            'set_gain_success': 'Set Gain Success',
            'set_offset_success': 'Set Offset Success',
            'set_usb_traffic_success': 'Set USB Traffic Success',
            'roi_activated': 'ROI mode activated, please click on the image to select the area',
            'roi_closed': 'ROI mode closed',
            'set_red_gain_success': 'Set Red Gain Success',
            'set_green_gain_success': 'Set Green Gain Success',
            'set_blue_gain_success': 'Set Blue Gain Success',
            'set_temperature_success': 'Set Temperature Success',
            'set_cfw_filter_success': 'Set CFW Filter Success',
            'camera_info_name': 'Camera Name',
            'camera_info_chip': 'Chip Size',
            'camera_info_image': 'Image Resolution',
            'camera_info_pixel': 'Pixel Size',
            'camera_info_disconnected': 'Disconnected',
            'start_recording': 'Start Recording',
            'recording_completed': 'Recording Completed',
            'stop_recording': 'Stop Recording',
            'settings_loaded': 'Settings Loaded',
            'update_camera_name': 'Rescan Camera',
            'update_readout_mode': 'Update Readout Mode:',
            'update_pixel_bin': 'Update Pixel Bin:',
            'update_depth': 'Update Depth:',
            'update_debayer_mode': 'Update Debayer Mode:',
            'fits_header': 'FITS Header',
            'fits_header_tooltip': 'Edit FITS Header',
            'quality_tooltip': 'Quality of the image, 0 is the lowest quality and 100 is the highest quality',
            'auto_exposure': 'Auto Exposure',
            'manual_auto_exposure': 'Manual Auto Exposure',
            'star_analysis': 'Star Analysis',
            'star_fwhm': 'Star FWHM:',
            'star_fwhm_tooltip': 'Star FWHM threshold',
            'save_star_table': 'Save Star Table',
            'auto_white_balance': 'Auto White Balance',
            'auto_white_balance_stop': 'Stop Auto White Balance',
            # 'set_qhyccd_auto_white_balance_success': 'Set QHYCCD Auto White Balance Success',
            'star_analysis_method': 'Star Analysis Method',
            'no_image_layer': 'No Image Layer',
            'prepare_to_star_analysis': 'Prepare to Star Analysis...',
            'star_analysis_completed': 'Star Analysis Completed!',
            'no_detected_stars': 'No Detected Stars',
            'cancel_solving': 'Cancel Solving.',
            'star_table_saved': 'Star Table Saved to',
        },
        'setting': {
            'settings': 'Settings',
            'language': 'Language',
            'apply': 'Apply',
            'cancel': 'Cancel',
            'reset': 'Reset',
            'settings_saved': 'Settings saved.',
            'settings_saved_message': 'Changes will take effect after restart.',
            'select_qhyccd_path': 'Select SDK Path',
        },
        'captureStatus': {
            'capturing': 'Capturing.. ',
            'capturing_1': 'Capturing.  ',
            'capturing_2': 'Capturing...',
            'exposure': 'Exposure:',
        },
        'histogramWidget': {
            'histogram': 'Histogram',
        },
        'camera_thread': {
            'start_connect': 'Start Connecting Camera...',
            'camera_connected_failed': 'Camera Connected Failed.',
            'camera_connected': 'Camera Connected Successfully.',
            'get_qhyccd_number_of_read_modes': 'Get QHYCCD Number Of Read Modes...',
            'get_qhyccd_number_of_read_modes_failed': 'Get QHYCCD Number Of Read Modes Failed.',
            'get_qhyccd_number_of_read_modes_success': 'Get QHYCCD Number Of Read Modes Successfully.',
            'set_qhyccd_read_mode': 'Set QHYCCD Read Mode...',
            'set_qhyccd_read_mode_failed': 'Set QHYCCD Read Mode Failed.',
            'set_qhyccd_read_mode_success': 'Set QHYCCD Read Mode Successfully.',
            'set_qhyccd_stream_mode': 'Set QHYCCD Stream Mode...',
            'set_qhyccd_stream_mode_failed': 'Set QHYCCD Stream Mode Failed.',
            'set_qhyccd_stream_mode_success': 'Set QHYCCD Stream Mode Successfully.',
            'init_camera': 'Init Camera...',
            'init_camera_failed': 'Init Camera Failed.',
            'init_camera_success': 'Init Camera Successfully.',
            'close_camera': 'Close Camera...',
            'close_camera_failed': 'Close Camera Failed.',
            'close_camera_success': 'Close Camera Successfully.',
            'release_camera_resource': 'Release Camera Resource...',
            'release_camera_resource_failed': 'Release Camera Resource Failed.',
            'release_camera_resource_success': 'Release Camera Resource Successfully.',
        },
        'fits_header': {
            'fits_header_editor': 'FITS Header Editor',
            'save_header': 'Save Header',
            'delete_header': 'Delete Header',
            'input_header_name': 'Input Header Name',
            'please_enter_header_name': 'Please Enter Header Name:',
            'confirm_delete': 'Confirm Delete',
            'confirm_delete_header': 'Confirm Delete Header',
        },
        'fits_header_defaults': {
            "standard": "Conforms to FITS standard",
            "data_type": "Array data type",
            "array_dimensions": "Number of array dimensions",
            "axis_length": "Length of data axis",
            "extensions": "Extensions may be present",
            "scaling_zero": "Zero point for scaling",
            "scaling_factor": "Scale factor for scaling",
            "observation_date": "Date of observation",
            "exposure_time": "Exposure time in seconds",
            "telescope": "Telescope name",
            "instrument": "Instrument used",
            "observer": "Observer name",
            "observed_object": "Object observed",
            "celestial_coordinate": "Celestial coordinate of observed object",
            "equinox": "Equinox of celestial coordinate system",
            "filter": "Filter used during observation",
            "airmass": "Airmass at time of observation",
            "sidereal_time": "Local Sidereal Time at start of observation",
            "detector_gain": "Detector gain",
            "read_noise": "Detector read noise",
            "transformation_matrix": "Transformation matrix element",
            "coordinate_type": "Type of coordinate",
            "reference_pixel": "Reference pixel",
            "coordinate_value": "Coordinate value at reference pixel",
            "coordinate_units": "Units of coordinate",
            "general_comment": "General comment",
            "processing_history": "Processing history"
        },
        'auto_exposure': {
            'auto_exposure': 'Auto Exposure',
            'manual_auto_exposure': 'Manual Auto Exposure',
            'mode_off': 'Off',
            'mode_gain_only': 'Gain Only',
            'mode_exp_only': 'Exposure Time Only',
            'mode_hybrid': 'Hybrid',
            'mode_all_day': 'All Day',
            'exposure_threshold': 'Exposure Threshold:',
            'gain_Max': 'Gain Max:',
            'no_mask': 'No Mask',
            'mask_a': 'Mask A',
            'mask_b': 'Mask B',
            'mask_a_tooltip': 'Center Position, 21.5% Coverage, Suitable for Large Targets',
            'mask_b_tooltip': 'Center Position, 5% Coverage, Suitable for Small Targets',
            'apply': 'Apply',
            'cancel': 'Cancel',
            'set_gain_max_error': 'Set Gain Max Error',
            'set_exposure_time_error': 'Set Exposure Time Error',
            'error': 'Error',
            'apply_success': 'Apply Success',
            'set_auto_exposure_mode_error': 'Set Auto Exposure Mode Error',
        },
        'auto_white_balance': {
            'auto_white_balance': 'Auto White Balance',
            'auto_white_balance_stop': 'Stop Auto White Balance',
            'set_qhyccd_auto_white_balance_success': 'Set QHYCCD Auto White Balance Success',
            'auto_white_balance_already_started': 'Auto White Balance Already Started',
        },
        'astrometry': {
            'title': 'Astrometry Parameters',
            'scale_units': 'Image Scale Units',
            'scale_units_tooltip': 'Image scale units, in degrees',
            'scale_units_tooltip_low': 'Lowest value',
            'scale_units_tooltip_high': 'Highest value',
            'uniformize_label': 'Uniformize',
            'uniformize_tooltip': 'Uniformize the image',
            'nsigmalimit_label': 'NSigma Limit',
            'nsigmalimit_tooltip': 'NSigma limit',
            'cpulimit_label': 'CPU Time Limit',
            'cpulimit_tooltip': 'CPU time limit in seconds',
            'local_angle_label': 'Location',
            'local_angle_tooltip_ra': 'Right Ascension',
            'local_angle_tooltip_dec': 'Declination',
            'local_angle_tooltip_radius': 'Radius',
            'overwrite_label': 'Overwrite',
            'overwrite_tooltip': 'Overwrite the existing file',
            'guess_the_scale_checkbox': 'Guess the scale',
            'guess_the_scale_tooltip': 'Guess the scale of the image',
            'reduce_pixel_size_checkbox': 'Reduce Pixel Size',
            'reduce_pixel_size_tooltip': 'Reduce the pixel size of the image',
            'timestamp_label': 'Timestamp',
            'timestamp_tooltip': 'Add timestamp to the image',
            'no_remove_lines_label': 'No Remove Lines',
            'no_remove_lines_tooltip': 'Do not remove lines',
            'resort_label': 'Resort',
            'resort_tooltip': 'Resort the image',
            'no_verify_checkbox': 'No Verify',
            'no_verify_label': 'No Verify',
            'no_verify_tooltip': 'Do not verify the WCS',
            'no_plots_label': 'No Plots',
            'no_plots_tooltip': 'Do not generate plots',
            'save_image_label': 'Save Image',
            'save_image_tooltip': 'Save the image',
            'save_image_path_label': 'Save Path:',
            'save_image_path_tooltip': 'Please enter the save path',
            'save_image_name_label': 'Image Name:',
            'save_image_name_tooltip': 'Please enter the image name',
            'submit_button': 'Submit',
            'warning': 'Warning',
            'save_image_path_and_name_cannot_be_empty': 'Save path and image name cannot be empty!',
            'invalid_image_input': 'Invalid image input',
            'failed_to_load_image_data': 'Failed to load image data',
            'solve_field_command_failed': 'solve-field command failed',
            'unexpected_error': 'Unexpected error',
            'tablist_command_failed': 'tablist command failed',
            'failed_to_save_image': 'Failed to save image',
            'failed_to_remove_temporary_files': 'Failed to remove temporary files',
            'failed_to_calculate_wcs': 'Failed to calculate WCS',
        },
        'debug': {
            'init_failed': 'Initialization Failed',
            'not_found_sdk': 'SDK file not found',
            'camera_connected_failed': 'Camera Connected Failed',
            'unknown_architecture': 'Unknown Architecture',
            'get_qhyccd_id_failed': 'Get QHYCCD ID Failed',
            'get_qhyccd_read_mode_number_failed': 'Get QHYCCD Read Mode Number Failed',
            'get_qhyccd_read_mode_name_failed': 'Get QHYCCD Read Mode Name Failed',
            'set_qhyccd_read_mode_failed': 'Set QHYCCD Read Mode Failed',
            'set_qhyccd_stream_mode_failed': 'Set QHYCCD Stream Mode Failed',
            'init_camera_failed': 'Init Camera Failed',
            'close_camera_failed': 'Close Camera Failed',
            'release_camera_resource_failed': 'Release Camera Resource Failed',
            'disconnect_white_balance_failed': 'Disconnect White Balance Failed',
            'get_qhyccd_param_failed': 'Get QHYCCD Param Failed',
            'get_qhyccd_is_color_camera_failed': 'Get QHYCCD Is Color Camera Failed',
            'get_qhyccd_effective_area_failed': 'Get QHYCCD Effective Area Failed',
            'get_qhyccd_chip_info_failed': 'Get QHYCCD Chip Info Failed',
            'set_qhyccd_bin_mode_failed': 'Set QHYCCD Bin Mode Failed',
            'set_qhyccd_transferbit_failed': 'Set QHYCCD Transferbit Failed',
            'set_qhyccd_resolution_failed': 'Set QHYCCD Resolution Failed',
            'get_qhyccd_param_min_max_step_failed': 'Get QHYCCD Param Min Max Step Failed',
            'set_qhyccd_exposure_time_failed': 'Set QHYCCD Exposure Time Failed',
            'set_qhyccd_gain_failed': 'Set QHYCCD Gain Failed',
            'set_qhyccd_offset_failed': 'Set QHYCCD Offset Failed',
            'set_qhyccd_usb_traffic_failed': 'Set QHYCCD USB Traffic Failed',
            'no_qhy_image': 'No QHY Image',
            'set_red_gain_failed': 'Set QHYCCD Red Gain Failed',
            'set_green_gain_failed': 'Set QHYCCD Green Gain Failed',
            'set_blue_gain_failed': 'Set QHYCCD Blue Gain Failed',
            'set_temperature_failed': 'Set QHYCCD Temperature Failed',
            'set_cfw_filter_failed': 'Set QHYCCD CFW Filter Failed',
            'begin_qhyccd_live_failed': 'Begin QHYCCD Live Failed',
            'stop_qhyccd_live_failed': 'Stop QHYCCD Live Failed',
            'exp_qhyccd_single_frame_failed': 'Exp QHYCCD Single Frame Failed',
            'get_qhyccd_single_frame_failed': 'Get QHYCCD Single Frame Failed',
            'save_image_failed': 'Save Image Failed',
            'set_qhyccd_debayer_mode_failed': 'Set QHYCCD Debayer Mode Failed',
            'set_qhyccd_auto_white_balance_failed': 'Set QHYCCD Auto White Balance Failed',

        },

    },
    'zh': {
        'qhyccd_capture': {
            'connect_settings': '连接设置',
            'settings': '设置',
            'status': '状态:',
            'select_camera': '选择相机:',
            'single_frame_mode': '单帧模式',
            'continuous_mode': '连续模式',
            'select_camera_mode': '选择相机模式:',
            'connect': '连接',
            'disconnect': '断开',
            'reset_camera': '重新扫描相机',
            'not_connected': '未连接',
            'fps': 'FPS: ~',
            'memory': '内存:',
            'show_camera_settings': '显示相机设置',
            'show_capture_control': '显示拍摄控制',
            'show_image_control': '显示图像控制',
            'show_temperature_control': '显示温度控制',
            'show_cfw_control': '显示滤镜轮控制',
            'show_video_control': '显示录像控制',
            'camera_settings': '相机设置',
            'readout_mode': '读出模式:',
            'pixel_bin': '像素合并 Bin:',
            'image_depth': '图像位深度:',
            'debayer_mode_true': '启动',
            'debayer_mode_false': '关闭',
            'debayer_mode': 'Debayer模式:',
            'set_resolution': '设置分辨率',
            'reset_resolution': '还原',
            'reset_resolution_tooltip': '还原为相机初始分辨率',
            'resolution': '分辨率',
            'roi': 'ROI',
            'roi_tooltip': 'ROI (鼠标第一次点击确定起始点，第二次点击确定终止点)',
            'x': 'x:',
            'y': 'y:',
            'w': 'w:',
            'h': 'h:',
            'capture_control': '拍摄控制',
            'exposure_time': '曝光时间:',
            'gain': '增益:',
            'offset': '偏移量:',
            'usb_traffic': 'USB 宽带:',
            'distributed_display': '分布式显示',
            'single_display': '单一显示',
            'sequential_display': '序列显示',
            'display_mode': '图像显示方式:',
            'bayer_conversion': 'Bayer 类型转换:',
            'start_capture': '开始拍摄',
            'save': '保存',
            'save_tooltip': '保存最后拍摄的未经过图像处理的图像',
            'recording': '录像',
            'preview_mode': '预览模式',
            'preview_mode_tooltip': '预览模式下，相机将实时输出图像数据，并显示在窗口中',
            'top_checkbox': '是否顶置',
            'top_checkbox_tooltip': '勾选后，图像将顶置显示',
            'single_frame_storage': '单帧存储',
            'video_storage': '视频存储',
            'save_mode': '保存方式:',
            'select_path': '选择路径',
            'record_path': '录像路径:',
            'record_file_name': '文件名:',
            'record_mode': '录像模式:',
            'time_mode': '时间模式',
            'frame_mode': '帧数模式',
            'seconds': ' 秒',
            'record_time': '录像时间:',
            'record_frames': '录像帧数:',
            'start_record': '开始录像',
            'stop_record': '停止录像',
            'record_progress': '录像进度:',
            'image_processing': '图像处理',
            'histogram': '直方图',
            'show_histogram': '显示直方图',
            'white_balance_control': '白平衡控制',
            'red': '红色:',
            'green': '绿色:',
            'blue': '蓝色:',
            'temperature_control': '温度控制',
            'set_temperature': '设置温度:',
            'temperature': '温度',
            'humidity': '湿度',
            'CFW_control': '滤镜轮控制',
            'CFW_position': '滤镜轮',
            'init_complete': '初始化完成',
            'connected': '连接相机完成',
            'disconnected': '断开相机连接',
            'capturing': '正在拍摄',
            'capture_complete': '拍摄完成',
            'update_camera_color': '判断是否为彩色相机',
            'update_limit_selector': '更新参数限制',
            'update_camera_config': '更新相机配置',
            'update_bin_mode': '更新bin模式',
            'update_depth_mode': '更新位深度',
            'update_resolution': '更新分辨率',
            'update_camera_mode': '更新相机模式',
            'update_temperature_control': '更新温度控制',
            'update_CFW_control': '更新滤镜轮控制',
            'set_resolution': '设置分辨率:',
            'cancel_capture': '取消拍摄',
            'capture_finished': '拍摄完成！',
            'capture_canceled': '拍摄已取消',
            'save_image': '保存图像',
            'save_image_failed': '图像保存失败',
            'apply_roi': '应用ROI',
            'select_save_path': '选择保存路径',
            'saving': '保存中...',
            'save_completed': '保存完成',
            'init_failed': '初始化失败',
            'save_image_success': '图像已保存到',
            'set_exposure_time_success': '设置曝光时间成功',
            'set_gain_success': '设置增益成功',
            'set_offset_success': '设置偏移量成功',
            'set_usb_traffic_success': '设置USB带宽成功',
            'roi_activated': 'ROI模式已激活，请在图像上点击以选择区域',
            'roi_closed': 'ROI模式已关闭',
            'set_red_gain_success': '设置红色增益成功',
            'set_green_gain_success': '设置绿色增益成功',
            'set_blue_gain_success': '设置蓝色增益成功',
            'set_temperature_success': '设置温度成功',
            'set_cfw_filter_success': '设置滤镜轮成功',
            'camera_info_name': '相机名称',
            'camera_info_chip': '芯片大小',
            'camera_info_image': '图像分辨率',
            'camera_info_pixel': '像素大小',
            'camera_info_disconnected': '未连接',
            'start_recording': '开始录像',
            'recording_completed': '录像完成',
            'stop_recording': '停止录像',
            'settings_loaded': '设置已加载',
            'update_camera_name': '重新扫描相机',
            'update_readout_mode': '更新读出模式:',
            'update_pixel_bin': '更新像素合并:',
            'update_depth': '更新位深度:',
            'update_debayer_mode': '更新Debayer模式:',
            'fits_header': 'FITS头文件',
            'fits_header_tooltip': '编辑FITS头文件',
            'quality_tooltip': '图像质量,0是最低质量,100是最高质量',
            'auto_exposure': '自动曝光',
            'manual_auto_exposure': '手动曝光',
            'star_analysis': '星点解析',
            'star_fwhm': '星点 FWHM:',
            'star_fwhm_tooltip': '星点 FWHM 阈值',
            'save_star_table': '保存星点表格',
            'auto_white_balance': '自动白平衡',
            'auto_white_balance_stop': '停止自动白平衡',
            # 'set_qhyccd_auto_white_balance_success': '设置自动白平衡成功',
            'star_analysis_method': '星点解析方法',
            'prepare_to_star_analysis': '准备进行星点解析...',
            'star_analysis_completed': '星点解析完成！',
            'no_detected_stars': '未检测到星点',
            'cancel_solving': '取消解析。',
            'star_table_saved': '星点表格已保存到',
            'no_image_layer': '没有图像图层',
        },       
        'setting': {
            'settings': '设置',
            'language': '语言',
            'apply': '应用',
            'cancel': '取消',
            'reset': '重置',
            'settings_saved': '设置已保存。',
            'settings_saved_message': '更改将在重启后生效。',
            'select_qhyccd_path': '选择SDK文件',
        },
        'captureStatus': {
            'capturing': '拍摄中.. ',
            'capturing_1': '拍摄中.  ',
            'capturing_2': '拍摄中...',
            'exposure': '曝光:',
        },
        'histogramWidget': {
            'histogram': '直方图',
        },
        'camera_thread': {
            'start_connect': '开始连接相机...',
            'camera_connected_failed': '相机连接失败',
            'camera_connected': '相机连接成功。',
            'get_qhyccd_number_of_read_modes': '获取相机读取模式数量...',
            'get_qhyccd_number_of_read_modes_failed': '获取相机读取模式数量失败。',
            'get_qhyccd_number_of_read_modes_success': '获取相机读取模式数量成功。',
            'set_qhyccd_read_mode': '设置相机读取模式...',
            'set_qhyccd_read_mode_failed': '设置相机读取模式失败。',
            'set_qhyccd_read_mode_success': '设置相机读取模式成功。',
            'set_qhyccd_stream_mode': '设置相机流模式...',
            'set_qhyccd_stream_mode_failed': '设置相机流模式失败。',
            'set_qhyccd_stream_mode_success': '设置相机流模式成功。',
            'init_camera': '初始化相机...',
            'init_camera_failed': '初始化相机失败。',
            'init_camera_success': '初始化相机成功。',
            'close_camera': '开始断开相机连接...',
            'close_camera_failed': '断开相机连接失败。',
            'close_camera_success': '断开相机连接成功。',
            'release_camera_resource': '释放资源...',
            'release_camera_resource_failed': '释放资源失败。',
            'release_camera_resource_success': '释放资源成功。',
        },
        'fits_header': {
            'fits_header_editor': 'FITS头文件编辑器',
            'save_header': '保存头文件',
            'delete_header': '删除头文件',
            'input_header_name': '输入头文件名称',
            'please_enter_header_name': '请输入头文件名称:',
            'confirm_delete': '确认删除',
            'confirm_delete_header': '确定要删除',
        },
        'fits_header_defaults': {
            "standard": "符合FITS标准",
            "data_type": "数组数据类型",
            "array_dimensions": "数组维度数量",
            "axis_length": "数据轴长度",
            "extensions": "可能存在扩展",
            "scaling_zero": "缩放零点",
            "scaling_factor": "缩放因子",
            "observation_date": "观测日期",
            "exposure_time": "曝光时间",
            "telescope": "望远镜名称",
            "instrument": "仪器使用",
            "observer": "观测者名称",
            "observed_object": "观测对象",
            "celestial_coordinate": "观测对象的天文坐标",
            "equinox": "观测对象的天文坐标系统",
            "filter": "观测时使用的滤镜",
            "airmass": "观测时的气团",
            "sidereal_time": "观测开始时的本地恒星时",
            "detector_gain": "探测器增益",
            "read_noise": "探测器读噪声",
            "transformation_matrix": "变换矩阵元素",
            "coordinate_type": "坐标类型",
            "reference_pixel": "参考像素",
            "coordinate_value": "参考像素的坐标值",
            "coordinate_units": "坐标单位",
            "general_comment": "通用注释",
            "processing_history": "处理历史"
        },
        'auto_exposure': {
            'auto_exposure': '自动曝光',
            'manual_auto_exposure': '手动曝光',
            'mode_off': '关闭',
            'mode_gain_only': '仅增益',
            'mode_exp_only': '仅曝光时间',
            'mode_hybrid': '混合',
            'mode_all_day': '全天',
            'exposure_threshold': '曝光阈值:',
            'gain_Max': '增益最大值:',
            'no_mask': '无遮罩图',
            'mask_a': '遮罩图 A',
            'mask_b': '遮罩图 B',
            'mask_a_tooltip': '中心位置, 占比 21.5%, 适合拍摄较大目标',
            'mask_b_tooltip': '中心位置, 占比 5%, 适合拍摄较小目标',
            'apply': '应用',
            'cancel': '取消',
            'set_gain_max_error': '设置增益最大值失败',
            'set_exposure_time_error': '设置曝光时间失败',
            'error': '错误',
            'apply_success': '应用成功',
            'set_auto_exposure_mode_error': '设置自动曝光模式失败',
        },
        'auto_white_balance': {
            'auto_white_balance': '自动白平衡',
            'auto_white_balance_stop': '停止自动白平衡',
            'set_qhyccd_auto_white_balance_success': '设置自动白平衡成功',
            'auto_white_balance_already_started': '自动白平衡已开始',
        },
        'astrometry': {
            'title': '星点解析参数设置',
            'scale_units': '图像缩放比例',
            'scale_units_tooltip': '图像缩放比例，单位为度',
            'scale_units_tooltip_low': '最小值',
            'scale_units_tooltip_high': '最大值',
            'uniformize_label': '均匀化标准',
            'uniformize_tooltip': '均匀化图像',
            'nsigmalimit_label': 'NSigma限制',
            'nsigmalimit_tooltip': 'NSigma限制',
            'cpulimit_label': 'CPU时间限制',
            'cpulimit_tooltip': 'CPU时间限制（秒）',
            'local_angle_label': '位置',
            'local_angle_tooltip_ra': '赤经',
            'local_angle_tooltip_dec': '赤纬',
            'local_angle_tooltip_radius': '半径',
            'overwrite_label': '是否覆盖现有文件',
            'overwrite_tooltip': '如果目标文件已存在，是否覆盖',
            'guess_the_scale_checkbox': '是否猜测图像缩放比例',
            'guess_the_scale_tooltip': '是否猜测图像缩放比例',
            'reduce_pixel_size_checkbox': '是否缩减像素采样',
            'reduce_pixel_size_tooltip': '是否缩减像素采样',
            'timestamp_label': '时间戳',
            'timestamp_tooltip': '是否添加时间戳',
            'no_remove_lines_label': '不移除行',
            'no_remove_lines_tooltip': '不移除行',
            'resort_label': '重新排序',
            'resort_tooltip': '是否按照亮度重新排序',
            'no_verify_checkbox': '不进行WCS验证',
            'no_verify_label': '不进行WCS验证',
            'no_verify_tooltip': '是否不进行WCS验证',
            'no_plots_label': '不生成图表',
            'no_plots_tooltip': '是否不生成图表',
            'save_image_label': '保存图像',
            'save_image_tooltip': '是否保存图像',
            'save_image_path_label': '保存路径:',
            'save_image_path_tooltip': '保存路径',
            'save_image_name_label': '保存文件名:',
            'save_image_name_tooltip': '保存文件名',
            'submit_button': '提交',
            'warning': '警告',
            'save_image_path_and_name_cannot_be_empty': '保存路径和图像名字不能为空！',
            'invalid_image_input': '无效的图像输入',
            'failed_to_load_image_data': '无法加载图像数据',
            'solve_field_command_failed': 'solve-field 命令失败',
            'unexpected_error': '意外错误',
            'tablist_command_failed': 'tablist 命令失败',
            'failed_to_save_image': '无法保存图像',
            'failed_to_remove_temporary_files': '无法删除临时文件',
            'failed_to_calculate_wcs': '无法计算WCS',
        },
        'debug': {
            'init_failed': '初始化失败',
            'not_found_sdk': '未找到SDK文件',
            'camera_connected_failed': '相机连接失败',
            'unknown_architecture': '未知的架构',
            'get_qhyccd_id_failed': '获取相机ID失败',
            'get_qhyccd_read_mode_number_failed': '获取相机读取模式数量失败',
            'get_qhyccd_read_mode_name_failed': '获取相机读取模式名称失败',
            'set_qhyccd_read_mode_failed': '设置相机读取模式失败',
            'set_qhyccd_stream_mode_failed': '设置相机流模式失败',
            'init_camera_failed': '初始化相机失败',
            'close_camera_failed': '关闭相机失败',
            'release_camera_resource_failed': '释放相机资源失败',
            'disconnect_white_balance_failed': '断开白平衡连接失败',
            'get_qhyccd_param_failed': '获取相机参数失败',
            'get_qhyccd_is_color_camera_failed': '获取相机颜色信息失败',
            'get_qhyccd_effective_area_failed': '获取相机有效区域失败',
            'get_qhyccd_chip_info_failed': '获取相机芯片信息失败',
            'set_qhyccd_bin_mode_failed': '设置相机bin模式失败',
            'set_qhyccd_transferbit_failed': '设置相机位深度失败',
            'set_qhyccd_resolution_failed': '设置相机分辨率失败',
            'get_qhyccd_param_min_max_step_failed': '获取相机参数最小值、最大值、步长失败',
            'set_qhyccd_exposure_time_failed': '设置相机曝光时间失败',
            'set_qhyccd_gain_failed': '设置相机增益失败',
            'set_qhyccd_offset_failed': '设置相机偏移量失败',
            'set_qhyccd_usb_traffic_failed': '设置相机USB带宽失败',
            'no_qhy_image': '没有以QHY开头的图片，无法启动ROI模式',
            'set_qhyccd_red_gain_failed': '设置相机红色增益失败',
            'set_qhyccd_green_gain_failed': '设置相机绿色增益失败',
            'set_qhyccd_blue_gain_failed': '设置相机蓝色增益失败',
            'set_qhyccd_temperature_failed': '设置相机温度失败',
            'set_qhyccd_cfw_filter_failed': '设置相机滤镜轮失败',
            'begin_qhyccd_live_failed': '开始预览失败',
            'stop_qhyccd_live_failed': '停止预览失败',
            'exp_qhyccd_single_frame_failed': '单帧曝光失败',
            'get_qhyccd_single_frame_failed': '获取单帧图像数据失败',
            'save_image_failed': '图像保存失败',
            'set_qhyccd_debayer_mode_failed': '设置相机Debayer模式失败',
            'set_qhyccd_auto_white_balance_failed':  '设置自动白平衡失败'
        },
    },
}